import { Analytics } from "@vercel/analytics/react";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  home,
}: {
  children: React.ReactNode;
  home?: boolean;
}) {
  console.log("### RootLayout: ", JSON.stringify(home));
  return (
    <html lang="en">
      <body>
        <div className="relative flex min-h-screen flex-col">{children}</div>
        <div>Is it home page: {home ? "it is" : "it's not"}</div>
        <Analytics />
      </body>
    </html>
  );
}
